### ISSUE TITLE
Кондиционеры воздуха

### ISSUE THREAD

**Issue by Fuckershy** [Harroway/Bay12#12]
Выставление термостата на 0 градусов прекращает работу по охлаждению\нагреванию вне зависимости от текущей температуры.
П.С. И кондиционеры работают КРАЙНЕ медленно, хоть это не баг, а неприятная особенность.

**Comment by SpeedCrash100** [comment]
Абсолютный 0 не достич вот и кондиционер не охлаждает.

**Comment by Hanter0718** [comment]
Там шкала Цельсия.

**Comment by SpeedCrash100** [comment]
Фича.
