### ISSUE TITLE
Так выглядят все гарнитуры, интеркомы и рации:

### ISSUE THREAD

**Issue by Hanter0718** [Harroway/Bay12#17]
![image](https://cloud.githubusercontent.com/assets/1624581/17809982/e09e9bf6-6622-11e6-8c72-15b1e7f6f585.png)

**Comment by Fuckershy** [comment]
А еще так забагивают ПДА при попытках начать переписку. Не у всех, но случается.

**Comment by SpeedCrash100** [comment]
Во всём виноват хост

**Comment by FireFlashie** [comment]
Пофикшено еще аж в #10, просто вы мне обновление провести 2 дня подряд не давали.
