### ISSUE TITLE
Сервис канал - моча и анал.

### ISSUE THREAD

**Issue by AdskyMent** [Harroway/Bay12#21]
**Эх Дека,** герой моих детских грёз, гроза мудаков и причина девчачих слёз. Всё никак не слезешь с бееколёс.
Вербовщики бееигила сошли с ума и вербуют людей под нашим носом. Все мы знаем, что под носом у беефюрера полоска усов и там нечего ловить, по этому, его руки дотянулись до Деки.
**Первым делом,** террористы саботировали связь. **:v не комплиментарен :м, из-за чего пользоваться сервис каналом неудобно.** 

Сначала связь, а что будет дальше? Похищения с целью выкупа? Взрывы в шаттле прибытия? Выпиливание пончиков из брига? Дека, одумайся! Слава и честь!

___

:v = :м как :s = :ы

**Comment by SpeedCrash100** [comment]
FIXED
